# Generated by Django 4.2 on 2023-04-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='descripton',
            new_name='description',
        ),
    ]
